### ISSUE TITLE
Patch android so failed

### ISSUE THREAD

**Issue by flywingsky** [NixOS/patchelf#144]
After use --add--needed path so file, running on android device,it crashed,the error is dlopen failed: invalid ELF file "/data/app/com.test/lib/arm/libtest.so" load segment[8]: p_offset (0x353000) + p_filesz (0x1dc8) ( = 0x354dc8) past end of file (0x354dc8)

**Comment by dtzWill** [comment]
Two quick notes:

* Don't suppose you can share the input file it or one that causes the same problem?
* Perhaps an off-by-one error? The reported end of file and end of segment are the same, which seems like a lead...

**Comment by dtzWill** [comment]
Looks like a bug in bionic, fixed in 2015: https://android.googlesource.com/platform/bionic/+/93ce35434ca5af43a7449e289959543f0a2426fa%5E%21/#F0

**Comment by flywingsky** [comment]
Maybe it is a feature in Android new version!so would you support for android os?

**Comment by dtzWill** [comment]
Sorry, what are you asking?

To elaborate a bit, the linked commit to bionic (Android's "libc") confirms a few things:
* My suspicion of this being an off-by-one elsewhere was correct (lucky guess :grin:); the bug is not in patchelf as far as I can tell
* The bug should not occur in "recent" Android versions--any that include the fix, which is hopefully most of them since it was fixed in 2015 :)
* As I recall, the error message is only capable of being printed (look at the code) with those values when using a broken check-- so the fix is not just conveniently aligned with my hunch but also can't be printed at all with the "fixed"/current code, which is nice --no other bug can (reasonably) cause the error you're seeing.

So... things should work with "recent" Android, sorry that I don't know more specifically what that means.
Is this something you can test/explore?

**Comment by flywingsky** [comment]
okay！I will test again! Thks!
