### ISSUE TITLE
Query: When is the next release?

### ISSUE THREAD

**Issue by nehaljwani** [NixOS/patchelf#160]
The commit https://github.com/NixOS/patchelf/commit/327d80443672c397970738f9e216a7e86cbf3ad7 bumped he version to 0.10, but I don't see any corresponding tag or tarball at https://nixos.org/releases/patchelf/

Since the last release in Feb 2016, a significant number of commits have been merged, including https://github.com/NixOS/patchelf/pull/85 (which is important for https://github.com/numba/numba/issues/3400)

**Comment by domenkozar** [comment]
cc @edolstra

**Comment by mhsmith** [comment]
I would also like a release now that the very long-standing bug #10 has been fixed.

**Comment by Thaodan** [comment]
Any news on that?

**Comment by mikroskeem** [comment]
A tiny bump from me as well, asking about the new release.

**Comment by bhipple** [comment]
CC @edolstra a release of patchelf would be quite nice, since it'd allow us to cleanup several locations in NixPkgs where we manually fixup builds, such as [1], by using the cleaner `--allowed-rpath-prefixes` feature from https://github.com/NixOS/patchelf/pull/98.

This is particularly useful for users who are doing builds on standard linux distros without sandboxes enabled, since their binaries may discover all sorts of things in /usr/bin.

[1] https://github.com/NixOS/nixpkgs/blob/96b9d77dd8a9f72244ac31e28608582ffdb62c5a/pkgs/development/libraries/openldap/default.nix#L36-L37

**Comment by kbrowder** [comment]
Bump for ba2695a8110abbc8cc6baf0eea819922ee5007fa

**Comment by tomberek** [comment]
Ran into some issues where building master patchelf solved the problem and the nixpkgs version could not (thanks #84).

**Comment by booxter** [comment]
Got bitten by golang binaries broken unless I use the latest tip. We really need a new release.

**Comment by domenkozar** [comment]
Released by @edolstra at https://nixos.org/releases/patchelf/patchelf-0.10/
