### ISSUE TITLE
Please release a tarball that includes configure

### ISSUE THREAD

**Issue by sjackman** [NixOS/patchelf#29]
Thanks

**Comment by mentalisttraceur** [comment]
The correct/intended/best-practice usage of autotools is that the source release tarballs include the configure script.

This is one of the main advantages of autotools for over all of the other build tools like CMake/SCons/etc: the fact that autotools is meant to make it so that someone building a release from source never needs to install the actual build system - they just need a shell and make and a compiler and it all works.
