### ISSUE TITLE
Tests fail on Fedora ARM

### ISSUE THREAD

**Issue by jeremysanders** [NixOS/patchelf#8]
Patchelf fails to run its self tests correctly on Fedora Rawhide with ARMV7HL.
http://koji.fedoraproject.org/koji/taskinfo?taskID=5731866
https://bugzilla.redhat.com/show_bug.cgi?id=992432

This is presumably similar to the failure to run self tests on PPC:
https://bugzilla.redhat.com/show_bug.cgi?id=627370

**Comment by chewi** [comment]
What's the status here? Seems like I'm not the only one who needs this.

**Comment by sriemer** [comment]
@chewi The status is unchanged. I've implemented the new algorithm partially to hide additions in the alignment part at the end of the code and data LOAD areas and pass all tests on ARM and x86_64. But library injection with it is only really working for some games on my ARM based smart phone. I need to implement a second patch to add new LOAD areas for data and code if there is no space in alignment any more. These have to be added at the end of cause and NOT in front of all others (which is the problem with the current algorithm).

I haven't had the time/priority to implement the second part yet (as it works for my favourite game already). Are you interested in helping me with it?

I use this stuff for mobile game cheating on a Linux smart phone where LD_PRELOAD is forbidden for regular users (no, it's not Android). I'm the author of the best Linux Game Trainer "ugtrain" and co-maintainer for scanmem.

**Comment by chewi** [comment]
I'm afraid this lies outside my areas of expertise. Gentoo Linux provides prebuilt binaries for icedtea (Java) since it takes a long time to build and we use this to change the RPATH from /usr/lib/icedtea to /opt/icedtea. It still works without doing this but the package manager's preserved-libs feature gets a little upset if you install both. Not the end of the world. Thanks for the detail though, much appreciated.

**Comment by domenkozar** [comment]
For aarch64 see #80, armv7 is something hard to test in CI setting so closing.
